"""Hourly mean-reversion monitor — RSI signals via yfinance."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np
import pandas as pd
import yfinance as yf

from src.config import AppConfig, WatchlistItem


@dataclass
class Signal:
    """A trading signal generated by the mean-reversion monitor."""

    symbol: str
    risk: str
    action: str  # BUY, SELL, HOLD
    rsi: float
    price: float
    sma_20: float
    bb_upper: float
    bb_lower: float
    auto_execute: bool
    reason: str


def _compute_rsi(closes: pd.Series, period: int = 14) -> float:
    """Compute RSI for a price series.

    Args:
        closes: Series of closing prices.
        period: RSI lookback period.

    Returns:
        Most recent RSI value (0–100).
    """
    if len(closes) < period + 1:
        return 50.0
    delta = closes.diff().dropna()
    gain = delta.clip(lower=0)
    loss = (-delta).clip(lower=0)
    avg_gain = gain.rolling(window=period).mean().iloc[-1]
    avg_loss = loss.rolling(window=period).mean().iloc[-1]
    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return float(100 - (100 / (1 + rs)))


def _compute_bollinger(closes: pd.Series, period: int = 20) -> tuple[float, float, float]:
    """Compute Bollinger Bands.

    Args:
        closes: Series of closing prices.
        period: Rolling window period.

    Returns:
        Tuple of (sma, upper_band, lower_band).
    """
    if len(closes) < period:
        price = float(closes.iloc[-1])
        return price, price, price
    sma = closes.rolling(window=period).mean().iloc[-1]
    std = closes.rolling(window=period).std().iloc[-1]
    return float(sma), float(sma + 2 * std), float(sma - 2 * std)


def check_symbol(
    item: WatchlistItem,
    rsi_buy: float = 30.0,
    rsi_sell: float = 70.0,
    period: str = "3mo",
) -> Optional[Signal]:
    """Check a single watchlist symbol and generate a signal.

    Args:
        item: Watchlist item with symbol, risk, and auto_execute.
        rsi_buy: RSI threshold below which a BUY signal is generated.
        rsi_sell: RSI threshold above which a SELL signal is generated.
        period: yfinance download period string.

    Returns:
        Signal dataclass, or None if data could not be fetched.
    """
    try:
        ticker = yf.Ticker(item.symbol)
        hist = ticker.history(period=period)
        if hist.empty or len(hist) < 20:
            return None
        closes = hist["Close"]
        rsi = _compute_rsi(closes)
        price = float(closes.iloc[-1])
        sma, bb_upper, bb_lower = _compute_bollinger(closes)

        if rsi < rsi_buy:
            action = "BUY"
            reason = f"RSI={rsi:.1f} below buy threshold {rsi_buy}"
        elif rsi > rsi_sell:
            action = "SELL"
            reason = f"RSI={rsi:.1f} above sell threshold {rsi_sell}"
        else:
            action = "HOLD"
            reason = f"RSI={rsi:.1f} within neutral zone [{rsi_buy},{rsi_sell}]"

        return Signal(
            symbol=item.symbol,
            risk=item.risk,
            action=action,
            rsi=rsi,
            price=price,
            sma_20=sma,
            bb_upper=bb_upper,
            bb_lower=bb_lower,
            auto_execute=item.auto_execute,
            reason=reason,
        )
    except Exception:
        return None


def run_hourly_monitor(cfg: AppConfig) -> list[Signal]:
    """Run the full hourly mean-reversion monitor over all watchlist symbols.

    Generates BUY signals when RSI < threshold, SELL when RSI > threshold.
    Never executes automatically for HIGH risk symbols.

    Args:
        cfg: Application config with investment watchlist and RSI thresholds.

    Returns:
        List of Signal objects for each watchlist symbol.
    """
    signals: list[Signal] = []
    for item in cfg.investment.watchlist:
        signal = check_symbol(
            item,
            rsi_buy=cfg.investment.rsi_buy_threshold,
            rsi_sell=cfg.investment.rsi_sell_threshold,
        )
        if signal is not None:
            # Never auto-execute HIGH risk — override regardless of config
            if item.risk == "HIGH":
                signal.auto_execute = False
            signals.append(signal)
    return signals


def format_signals_table(signals: list[Signal]) -> str:
    """Format signals as a markdown table.

    Args:
        signals: List of Signal objects from run_hourly_monitor.

    Returns:
        Markdown-formatted table string.
    """
    if not signals:
        return "_No signals generated._\n"

    lines = [
        "| Symbol | Risk | Action | RSI | Price | Auto? | Reason |",
        "| ------ | ---- | ------ | --- | ----- | ----- | ------ |",
    ]
    for s in signals:
        auto = "Yes" if s.auto_execute else "No"
        lines.append(
            f"| {s.symbol} | {s.risk} | **{s.action}** | {s.rsi:.1f} | "
            f"${s.price:.2f} | {auto} | {s.reason} |"
        )
    return "\n".join(lines) + "\n"
